build_image:
  only:
    - develop
  script:
    - docker container stop ui
    - docker container rm ui
    - docker image rm khuvid19/coreui
    - docker build -t khuvid19/coreui .
    - docker run -d -it -p 20501:3000 --name ui khuvid19/coreui
  tags:
    - khuvid_front
