stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: <IP>:5000/nodejs-server-test:$IMAGE_VERSION

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: node:latest
  script:
    - env
    - yarn install
  tags:
    - khuvid_front

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - ls -al
    - docker container ls -a
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker images | grep '<IP>'
  tags:
    - khuvid_front

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker container ls -a
    - docker container rm -f nodejs-server
    - docker run -d -p 8090:8090 --name nodejs-server --restart always $IMAGE_NAME
    - docker container ls -a
  tags:
    - khuvid_front
